### ISSUE TITLE
python 2.7: The WaveConverter GUI requires matplotlib. Exiting...

### ISSUE THREAD

**Issue by geetee24** [paulgclark/waveconverter#10]
installed all and get:

The WaveConverter GUI requires matplotlib. Exiting...

Why?

tried this too 

PYTHONPATH=/home/aaaa/code:/home/aaaaa/code/rf_utilities:/home/aaa/code/waveconverter/src:/usr/lib/pyton2.7/dist-packages/matplotlib

not worl

**Comment by geetee24** [comment]
fixed typo in pyton to python and now get this error

Traceback (most recent call last):
  File "./waveconverter.py", line 13, in <module>
    import argparse
  File "/usr/lib/python2.7/argparse.py", line 85, in <module>
    import collections as _collections
  File "/usr/lib/python2.7/dist-packages/matplotlib/collections.py", line 22, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 74, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/usr/lib/python2.7/dist-packages/numpy/testing/__init__.py", line 10, in <module>
    from unittest import TestCase
  File "/usr/lib/python2.7/unittest/__init__.py", line 58, in <module>
    from .result import TestResult
  File "/usr/lib/python2.7/unittest/result.py", line 9, in <module>
    from . import util
  File "/usr/lib/python2.7/unittest/util.py", line 2, in <module>
    from collections import namedtuple, OrderedDict
ImportError: cannot import name namedtuple
