### ISSUE TITLE
Unable to see baseband signal.

### ISSUE THREAD

**Issue by bdn76** [paulgclark/waveconverter#4]
From readme:

./waveconverter.py -q ../input_files/fan_all_dip1101_pruned_dec_c304p55M_s830k.iq -o ../output_files/test.log -g -p 3
304550000.0
attempting to retrieve protocol 3 from database
Traceback (most recent call last):
  File "/home/dima/src/waveconverter/src/waveconverter_gui.py", line 380, in on_transmissionNumberSelect_value_changed
    self.changeTxNumberToView(txNum)
  File "/home/dima/src/waveconverter/src/waveconverter_gui.py", line 330, in changeTxNumberToView
    self.drawBasebandPlot(wcv.txList[wcv.txNum].waveformData, 
IndexError: list index out of range

and GUI not work.

**Comment by paulgclark** [comment]
Thanks for the bug report. One clarifying question: did the error occur immediately after hitting enter on the command line? Or did you click anything in the GUI first?

**Comment by bdn76** [comment]
First one.

**Comment by mnaujokas** [comment]
I'm experiencing exactly the same issue, any workarounds yet?

**Comment by paulgclark** [comment]
I tried to reproduce this error with the following steps:
- installing Ubuntu 16.01 LTS on a fresh partition
- installing all system updates
- installing gnuradio via pybombs (instructions at http://www.fieldxp.com/Chapter-2-Installing-the-Software.pdf)
- installing other pre-reqs listed in README
- running the following:
./waveconverter.py -q ../input_files/fan_all_dip1101_pruned_dec_c304p55M_s830k.iq -o ../output_files/test.log -g -p 3

I did see the "list index out of range" error, which must have slipped past my last regression. This error, however, did not impact anything, and I was able to hit the demod button and see the baseband waveform.

mnaujokas - does anything happen when you hit the demod button?
bdn76 - can you tell me anything about your setup? for example, how did you install gnuradio?

Thanks for your patience all.
PC
