### ISSUE TITLE
is not running

### ISSUE THREAD

**Issue by m4l490n** [paulgclark/waveconverter#5]
I get the following error when trying to run:

Traceback (most recent call last):
  File "./waveconverter.py", line 18, in <module>
    import waveConvertVars as wcv
  File "/home/mmalagon/waveconverter/src/waveConvertVars.py", line 3, in <module>
    from waveconverterEngine import packetsToFormattedString
  File "/home/mmalagon/waveconverter/src/waveconverterEngine.py", line 229, in <module>
    from demod_rf import ook_flowgraph
  File "/home/mmalagon/waveconverter/src/demod_rf.py", line 10, in <module>
    from gnuradio import gr
ImportError: No module named gnuradio

**Comment by aurelihein** [comment]
hi,
sudo apt-get install gnuradio
Should solve your problem
Regards

2017-01-17 15:36 GMT+01:00 m4l490n <notifications@github.com>:

**Comment by paulgclark** [comment]
Thanks for adding the info, aurelihein.

Installing gnuradio with apt-get should work, but it may hinder you a bit if you want to use gnuradio for other things because it installs an older version of the software. To build the latest release, you can follow the instructions here:
http://www.fieldxp.com/Chapter-2-Installing-the-Software.pdf

It will take a bit more effort, but your install will include some new and cool stuff.
